create extension if not exists "pgcrypto";

do $$
begin
  if not exists (select 1 from pg_type where typname = 'app_role') then
    create type public.app_role as enum (
      'dev',
      'admin',
      'diretoria',
      'gerente',
      'gerente_marketing',
      'gestor_trafego',
      'vendedor',
      'pre_venda'
    );
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'lead_status') then
    create type public.lead_status as enum ('novo', 'em_contato', 'cliente', 'inativo');
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'opportunity_status') then
    create type public.opportunity_status as enum (
      'orcamento',
      'negociacao',
      'ganho',
      'perdido'
    );
  end if;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  role public.app_role not null default 'vendedor',
  full_name text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.login_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users on delete cascade,
  logged_at timestamptz not null default now(),
  ip_address text,
  user_agent text
);

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  manager_id uuid references auth.users,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.team_members (
  team_id uuid not null references public.teams on delete cascade,
  user_id uuid not null references auth.users on delete cascade,
  created_at timestamptz not null default now(),
  primary key (team_id, user_id)
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  phone text,
  city text,
  state text,
  origin text,
  owner_id uuid references auth.users,
  status public.lead_status not null default 'novo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.opportunities (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references public.leads on delete cascade,
  segment text not null,
  product text not null,
  stage public.opportunity_status not null default 'orcamento',
  owner_id uuid references auth.users,
  amount numeric(12, 2) not null default 0,
  budget_number bigint generated by default as identity,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (budget_number)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_teams_updated_at on public.teams;
create trigger set_teams_updated_at
before update on public.teams
for each row execute function public.set_updated_at();

drop trigger if exists set_leads_updated_at on public.leads;
create trigger set_leads_updated_at
before update on public.leads
for each row execute function public.set_updated_at();

drop trigger if exists set_opportunities_updated_at on public.opportunities;
create trigger set_opportunities_updated_at
before update on public.opportunities
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data ->> 'full_name')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.has_role(required_role public.app_role)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = required_role
  );
$$;

create or replace function public.has_any_role(required_roles public.app_role[])
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = any(required_roles)
  );
$$;

create or replace function public.is_manager_of(member_id uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.teams t
    join public.team_members tm on tm.team_id = t.id
    where t.manager_id = auth.uid()
      and tm.user_id = member_id
  );
$$;

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
  user_role public.app_role;
begin
  select p.role into user_role
  from public.profiles p
  where p.id = (event ->> 'user_id')::uuid;

  return jsonb_build_object(
    'claims',
    jsonb_build_object('role', coalesce(user_role, 'vendedor'::public.app_role))
  );
end;
$$;

alter table public.profiles enable row level security;
alter table public.login_history enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.leads enable row level security;
alter table public.opportunities enable row level security;

drop policy if exists "profiles_read" on public.profiles;
create policy "profiles_read"
on public.profiles
for select
using (
  public.has_any_role(array['dev', 'admin'])
  or id = auth.uid()
);

drop policy if exists "profiles_update" on public.profiles;
create policy "profiles_update"
on public.profiles
for update
using (
  public.has_any_role(array['dev', 'admin'])
  or id = auth.uid()
);

drop policy if exists "profiles_insert" on public.profiles;
create policy "profiles_insert"
on public.profiles
for insert
with check (public.has_any_role(array['dev', 'admin']));

drop policy if exists "login_history_read" on public.login_history;
create policy "login_history_read"
on public.login_history
for select
using (
  public.has_any_role(array['dev', 'admin'])
  or user_id = auth.uid()
);

drop policy if exists "login_history_insert" on public.login_history;
create policy "login_history_insert"
on public.login_history
for insert
with check (user_id = auth.uid());

drop policy if exists "teams_read" on public.teams;
create policy "teams_read"
on public.teams
for select
using (
  public.has_any_role(array['dev', 'admin'])
  or manager_id = auth.uid()
  or exists (
    select 1
    from public.team_members tm
    where tm.team_id = id and tm.user_id = auth.uid()
  )
);

drop policy if exists "teams_write" on public.teams;
create policy "teams_write"
on public.teams
for all
using (public.has_any_role(array['dev', 'admin']) or manager_id = auth.uid())
with check (public.has_any_role(array['dev', 'admin']) or manager_id = auth.uid());

drop policy if exists "team_members_read" on public.team_members;
create policy "team_members_read"
on public.team_members
for select
using (
  public.has_any_role(array['dev', 'admin'])
  or exists (
    select 1
    from public.teams t
    where t.id = team_id and t.manager_id = auth.uid()
  )
  or user_id = auth.uid()
);

drop policy if exists "team_members_write" on public.team_members;
create policy "team_members_write"
on public.team_members
for all
using (
  public.has_any_role(array['dev', 'admin'])
  or exists (
    select 1
    from public.teams t
    where t.id = team_id and t.manager_id = auth.uid()
  )
)
with check (
  public.has_any_role(array['dev', 'admin'])
  or exists (
    select 1
    from public.teams t
    where t.id = team_id and t.manager_id = auth.uid()
  )
);

drop policy if exists "leads_read" on public.leads;
create policy "leads_read"
on public.leads
for select
using (
  public.has_any_role(array['dev', 'admin'])
  or public.has_any_role(array['diretoria', 'gerente_marketing', 'gestor_trafego'])
  or owner_id = auth.uid()
  or public.is_manager_of(owner_id)
  or (public.has_role('pre_venda') and owner_id is null)
);

drop policy if exists "leads_insert" on public.leads;
create policy "leads_insert"
on public.leads
for insert
with check (auth.uid() is not null);

drop policy if exists "leads_update" on public.leads;
create policy "leads_update"
on public.leads
for update
using (
  public.has_any_role(array['dev', 'admin'])
  or owner_id = auth.uid()
  or public.is_manager_of(owner_id)
  or (public.has_role('pre_venda') and owner_id is null)
)
with check (
  public.has_any_role(array['dev', 'admin'])
  or owner_id = auth.uid()
  or public.is_manager_of(owner_id)
  or (public.has_role('pre_venda') and owner_id is null)
);

drop policy if exists "leads_delete" on public.leads;
create policy "leads_delete"
on public.leads
for delete
using (public.has_any_role(array['dev', 'admin']));

drop policy if exists "opportunities_read" on public.opportunities;
create policy "opportunities_read"
on public.opportunities
for select
using (
  public.has_any_role(array['dev', 'admin'])
  or public.has_any_role(array['diretoria', 'gerente_marketing', 'gestor_trafego'])
  or owner_id = auth.uid()
  or public.is_manager_of(owner_id)
  or (public.has_role('pre_venda') and owner_id is null)
);

drop policy if exists "opportunities_insert" on public.opportunities;
create policy "opportunities_insert"
on public.opportunities
for insert
with check (auth.uid() is not null);

drop policy if exists "opportunities_update" on public.opportunities;
create policy "opportunities_update"
on public.opportunities
for update
using (
  public.has_any_role(array['dev', 'admin'])
  or owner_id = auth.uid()
  or public.is_manager_of(owner_id)
  or (public.has_role('pre_venda') and owner_id is null)
)
with check (
  public.has_any_role(array['dev', 'admin'])
  or owner_id = auth.uid()
  or public.is_manager_of(owner_id)
  or (public.has_role('pre_venda') and owner_id is null)
);

drop policy if exists "opportunities_delete" on public.opportunities;
create policy "opportunities_delete"
on public.opportunities
for delete
using (public.has_any_role(array['dev', 'admin']));
